# Use the latest postgres image as the base
FROM postgres:latest

# Export port 5432
EXPOSE 5432

RUN echo ">>>>>>" "$POSTGRES_PASSWORD"

# Set labels
LABEL maintainer="agiraude"
LABEL email="agiraude@student.42.fr"
